
services:
  # =========================
  # DISCOVERY SERVICE
  # =========================
  discovery-service:
    build: ./Discovery-service
    container_name: discovery-service
    ports:
      - "${DISCOVERY_PORT}:8761"
    networks:
      - medilabo-network

    restart: unless-stopped


  # =========================
  # GATEWAY (point d'entrée)
  # =========================
  gateway:
    build: ./Gateway-service
    container_name: gateway
    ports:
      - "${GATEWAY_PORT}:8080"
    environment:
      - JWT_SECRET=${JWT_SECRET}
      - jwt.expiration=${JWT_EXPIRATION}
      - DISCOVERY_URL=${DISCOVERY_URL}
    depends_on:
      - discovery-service
    networks:
      - medilabo-network

    restart: unless-stopped

  # =========================
  # FRONTEND
  # =========================
  frontend-service:
    build: ./Frontend-service
    container_name: frontend-service
    ports:
      - "${FRONT_PORT}:8082"
    environment:
      - JWT_SECRET=${JWT_SECRET}
      - jwt.expiration=${JWT_EXPIRATION}
      - DISCOVERY_URL=${DISCOVERY_URL}
    depends_on:
      - gateway
    networks:
      - medilabo-network

    restart: unless-stopped

  # =========================
  # PATIENT SERVICE
  # =========================
  patient-service:
    build: ./Patient-service
    container_name: patient-service
    expose:
      - "${PATIENT_PORT}"
    environment:
      - JWT_SECRET=${JWT_SECRET}
      - jwt.expiration=${JWT_EXPIRATION}
      - spring.datasource.url=${DB_PATIENTS_URL}
      - spring.datasource.username=${DB_USERNAME}
      - spring.datasource.password=${DB_PASSWORD}
      - DISCOVERY_URL=${DISCOVERY_URL}
    depends_on:
      - discovery-service
      - gateway
      - mysql-patients
    networks:
      - medilabo-network

    restart: unless-stopped



  # =========================
  # History SERVICE (MongoDB)
  # =========================
  history-service:
    build: ./History-service
    container_name: history-service
    expose:
      - "${HISTORY_PORT}"
    environment:
      - MONGO_URI=${MONGO_URI}
      - JWT_SECRET=${JWT_SECRET}
      - jwt.expiration=${JWT_EXPIRATION}
      - DISCOVERY_URL=${DISCOVERY_URL}
    depends_on:
      - discovery-service
      - gateway
      - mongodb
    networks:
      - medilabo-network


    restart: unless-stopped

  # =========================
  # EVALUATION SERVICE
  # =========================
  evaluation-service:
    build: ./Evaluation-Service
    container_name: evaluation-service
    expose:
      - "${EVALUATION_PORT}"
    environment:
      - JWT_SECRET=${JWT_SECRET}
      - jwt.expiration=${JWT_EXPIRATION}
      - DISCOVERY_URL=${DISCOVERY_URL}
    depends_on:
      - discovery-service
      - patient-service
      - history-service
      - gateway
    networks:
      - medilabo-network

    restart: unless-stopped

  # =========================
  # SECURITY SERVICE
  # =========================
  security-service:
    build: ./Security-service
    container_name: security-service
    expose:
    - "${SECURITY_PORT}"
    environment:
    - JWT_SECRET=${JWT_SECRET}
    - jwt.expiration=${JWT_EXPIRATION}
    - spring.datasource.url=${DB_SECURITY_URL}
    - spring.datasource.username=${DB_USERNAME}
    - spring.datasource.password=${DB_PASSWORD}
    - DISCOVERY_URL=${DISCOVERY_URL}
    depends_on:
    - discovery-service
    - mysql-security
    - gateway
    networks:
    - medilabo-network
    restart: unless-stopped





  # =========================
  # MONGODB
  # =========================
  mongodb:
    image: mongo:6
    container_name: mongodb
    volumes:
      - mongo_data:/data/db
    networks:
      - medilabo-network


    restart: unless-stopped


  #===========================
  # PATIENTS DB (MySQL)
  #===========================
  mysql-patients:
    image: mysql:8
    container_name: mysql_patients

    environment:
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
      - MYSQL_DATABASE=patients_db

    networks:
        - medilabo-network


    restart: unless-stopped

  #===========================
  # SECURITY DB (MySQL)
  #===========================
  mysql-security:
    image: mysql:8
    container_name: mysql_security
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
      - MYSQL_DATABASE=security_db

    networks:
        - medilabo-network


    restart: unless-stopped

# =========================
# VOLUMES
# =========================
volumes:
  mongo_data:



# =========================
# NETWORK
# =========================
networks:
  medilabo-network:
    driver: bridge