spring.application.name=Gateway-service
server.port=8080
eureka.client.service-url.defaultZone=http://localhost:8761/eureka
logging.level.org.springframework.cloud.gateway=INFO
logging.level.org.springframework.cloud.netflix.eureka=INFO
spring.cloud.gateway.routes[0].id=patient-service-api
spring.cloud.gateway.routes[0].uri=lb://PATIENT-SERVICE
spring.cloud.gateway.routes[0].predicates[0]=Path=/patients/**
spring.cloud.gateway.routes[0].filters[0]=StripPrefix=2
