spring.application.name=Evaluation-Service
server.port=8085

#Eureka configuration

eureka.client.service-url.defaultZone=${DISCOVERY_URL}
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
eureka.client.registry-fetch-interval-seconds=5

#JWT configuration
jwt.expiration=${jwt.expiration}
jwt.secret=${JWT_SECRET}