spring.application.name=Patient-service
server.port=8081


# Database configuration
spring.datasource.url=${DB_PATIENTS_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.hikari.initializationFailTimeout=60000
spring.datasource.hikari.connectionTimeout=30000

# flyway configuration

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration
logging.level.org.flywaydb=DEBUG

# JPA configuration
spring.jpa.hibernate.ddl-auto=none



#Eureka configuration

eureka.client.service-url.defaultZone=${DISCOVERY_URL}
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
eureka.client.registry-fetch-interval-seconds=5

#JWT configuration
jwt.expiration=${jwt.expiration}
jwt.secret=${JWT_SECRET}


